[package]
name = "prover-cluster"
version = "0.1.0"
authors = ["HAOYUatHZ <haoyu@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.5"
log = "0.4"

[[bin]]
name = "coordinator"
path = "src/bin/coordinator.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
