version: '3.4'

x-envs:
  &log-env
  RUST_LOG: info,sqlx=warn
  RUST_BACKTRACE: 1

x-clients:
  &client-config
  image: prover-cli
  build:
    context: .
    dockerfile: ./images/cluster_client_test.docker
  depends_on:
    - "coordinator"
  volumes:
    - ./config/client.yaml:/opt/client.yaml

services:
  db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: exchange_pq
    restart: always
    volumes:
      - ~/data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prover_cluster
      POSTGRES_USER: coordinator
      POSTGRES_PASSWORD: coordinator_AA9944

  coordinator:
    image: prover-coordinator
    build:
      context: .
      dockerfile: ./images/cluster_coordinator.docker
  #   args:
  #     buildno: 1
    depends_on:
      - "db"
    container_name: cluster_coordinator
    environment: 
      << : *log-env
    volumes:
      - ./config/coordinator.yaml:/opt/coordinator.yaml

  client1:
    << : *client-config
    environment: 
      << : *log-env
      CLIENT_PROVER_ID: x1    

  client2:
    << : *client-config
    environment: 
      << : *log-env
      CLIENT_PROVER_ID: x2

  client3:
    << : *client-config
    environment: 
      << : *log-env
      CLIENT_PROVER_ID: x3